from woocommerce import API
import csv
from time import sleep
import re

def GetAPIConnect():
    wcapi = API(
        url="https://t.parfumelight.ru",
        consumer_key="ck_e9a9cd7d5bec35dd781de2ca343bb549bbfb38c3",
        consumer_secret="cs_0400759a72f786596bb9fe97ab6546239d54f9c1",

        # url="http://roma28.beget.tech",
        # consumer_key="ck_aa7763a2a2b844b03fdd67a3aa752812922ac5ab",
        # consumer_secret="cs_04eda7aa92e03331b14e581eb60fbd02494b81a3",

        # url = "https://parfumlight.ru",
        # consumer_key="ck_3b314154d5a13a02e953c5c9b6872dc6c728ee88",
        # consumer_secret="cs_e63be44fd4f9915e232fe8fc87754a30017f6886",
        version="wc/v3",
        timeout = 18
    )
    return wcapi

def GetOLDTovar(wcapi):
    page = 1
    dataproducts = []
    while True:
        products = wcapi.get('products', params={'per_page': 100, "type":"grouped",'stock_status': 'instock', 'page': page}).json()
        # print(products)
        for i in products:
            # print(i)
            # print(i.get("name"))
            # print(i.get("grouped_products"))
            dataproducts.append({
                "id": i.get("id"),
                "name" : i.get("name"),
                "grouped_products" : i.get("grouped_products"),
                "images": i.get("images"),
                "description": i.get("description"),
                "categories": i.get("categories"),
            })
        if len(products) == 0:  # no more products
            break
        page = page + 1

    return dataproducts

def RenameName(name,brands):
    if name.count("(w)")>0:
        pol = "Женская парфюмерия"
        name = name.replace("(w)",'')
    elif name.count("(m)") > 0:
        pol = "Мужская парфюмерия"
        name = name.replace("(m)", '')
    elif name.count("(y)") > 0:
        pol = "Унисекс"
        name = name.replace("(y)", '')
    else:
        pol = "Унисекс"
    if name.count("edp") > 0:
        vid = "Парфюмерная вода"
        name = name.replace("edp", '')
    elif name.count("edc") > 0:
        vid = "Одеколон"
        name = name.replace("edc", '')
    elif name.count("edt") > 0:
        vid = "Туалетная вода"
        name = name.replace("edt", '')
    elif name.count("parfume") > 0:
        vid = "Парфюм"
        name = name.replace("parfume", '')
    else:
        vid = ""

    BRAND = ["A Lab on Fire",
             "Abercrombie & Fitch",
             "Absolument Parfumeur",
             "Acca Kappa",
             "Accendis",
             "Acqua dell Elba",
             "Acqua Delle Langhe",
             "Acqua Di Biella",
             "Acqua Di Genova",
             "Acqua di Monaco",
             "Acqua Di Parma",
             "Acqua Di Portofino",
             "Acqua di Sardegna",
             "Acqua di Stresa",
             "Acqua Reale",
             "Adam Levine",
             "Adidas",
             "Adolfo Dominguez",
             "Adriano Domianni",
             "Adrienne Vittadini",
             "Aedes de Venustas",
             "Aerin Lauder",
             "Aether",
             "Affinessence",
             "Afnan",
             "Agatha Paris",
             "Agatha Ruiz De La Prada",
             "Agatho Parfum",
             "Agent Provocateur",
             "Agnes B",
             "Agonist",
             "Ahjaar",
             "Aigner",
             "Air-Val International",
             "AJ Arabia",
             "Ajmal",
             "Ajne",
             "Ajyad",
             "AK France",
             "Akro",
             "Al Hamatt",
             "Al Haramain",
             "Al Marjaan",
             "Al-Rehab",
             "Alaia",
             "Alain Aregon",
             "Alain Delon",
             "Alan Bray",
             "Albert Nipon",
             "Alberta Ferretti",
             "Albin Du Roy",
             "Alessandro Dell Acqua",
             "Alessandro Della Torre",
             "Alex Simone",
             "Alexa Lixfeld",
             "Alexander Mcqueen",
             "Alexandre J",
             "Alfred Sung",
             "Alghabra Parfums",
             "Alla Pugachova",
             "Altro Aroma",
             "Alviero Martini",
             "Alyson Oldoini",
             "Alyssa Ashley",
             "American Eagle",
             "Amorino Prive",
             "Amouage",
             "Amouroud",
             "Amway",
             "Anat Fritz",
             "Andre D`Archer",
             "Andrea Maack",
             "Andree Putman",
             "Andy Warhol",
             "Anfas Alkhaleej Perfumes",
             "Ange Lapin",
             "Angel Schlesser",
             "Angela Ciampagna",
             "Angry Birds",
             "Anima Mundi",
             "Animale",
             "Ann Gerard",
             "Anna Paghera",
             "Anna Sui",
             "Annayake",
             "Anne Fontaine",
             "Anne Klein",
             "Anne Moller",
             "Annick Goutal",
             "Antonia's Flowers",
             "Antonio Alessandria",
             "Antonio Banderas",
             "Antonio Fusco",
             "Antonio Puig",
             "Antonio Visconti",
             "Anucci",
             "Apple Parfums",
             "April Aromatics",
             "Aquolina",
             "Arabesque",
             "Arabian Oud",
             "Aramis",
             "Ard Al Zaafaran",
             "Ariana Grande",
             "Armaf",
             "Armand Basi",
             "Armorial",
             "Arno Sorel",
             "Arrogance",
             "Arte Profumi",
             "ArteOlfatto",
             "Asayel",
             "Asgharali",
             "Aster Perfumes",
             "Atelier Cologne",
             "Atelier des Ors",
             "Atelier Flou",
             "Atelier Materi",
             "Atkinsons",
             "Attar Collection",
             "Au Pays De La Fleur d`Oranger",
             "Aubusson",
             "Austin Reed",
             "Avery Fine Perfumery",
             "Avril Lavigne",
             "Axis",
             "Azagury",
             "Azzaro",
             "B&B Cosmetics",
             "B'Prime Perfume",
             "B.u",
             "Badgley Mischka",
             "Baldi",
             "Baldinini",
             "Balenciaga",
             "Bamotte",
             "Banana Republic",
             "Barbie",
             "Barneys New York",
             "Bath And Body Works",
             "BeauFort London",
             "Bebe",
             "Bejar",
             "Bellegance",
             "Benefit",
             "Benetton",
             "Bernd Berger",
             "Beso Beach Perfumes",
             "Betsey Johnson",
             "Betty Barclay",
             "Betty Boop",
             "Beyonce",
             "Bharara Beauty",
             "Biehl",
             "Bijan",
             "Bill Blass",
             "Biotherm",
             "Bjork & Berries",
             "Blackglama",
             "Blend Oud",
             "Bliss Perfumes",
             "Blood Concept",
             "Blumarine",
             "Boadicea the Victorious",
             "Bob Mackie",
             "Bobbi Brown",
             "Bogart",
             "Bogner",
             "BOIS 1920",
             "Bond No. 9",
             "Borghese",
             "Borsalino",
             "Borsari",
             "Botanicae Expressions",
             "Bottega Profumiera",
             "Bottega Veneta",
             "Boucheron",
             "Bouge",
             "Bourjois",
             "Braccialini",
             "Brecourt",
             "Breil Milano",
             "Britney Spears",
             "Brocard",
             "Brooks Brothers",
             "Bruce Oldfield",
             "Bruno Banani",
             "Brut",
             "Bsq",
             "Burberry",
             "Burdin",
             "Butterfly",
             "Bvlgari",
             "Byblos",
             "ByBozo",
             "Byredo Parfums",
             "Cacharel",
             "Caesars",
             "Cafe-cafe",
             "Cale Fragranze d’Autore",
             "Calligraphy",
             "Calvin Klein",
             "Calyx",
             "Campos De Ibiza",
             "Cardio Bunny",
             "Carine Roitfeld",
             "Carita",
             "Carla Fracci",
             "Carlos Campos",
             "Carlos Santana",
             "Carner Barcelona",
             "Carolina Herrera",
             "Carolyn Murphy",
             "Caron",
             "Carrement Belle",
             "Carrera",
             "Carthusia",
             "Cartier",
             "Carven",
             "Castelbajac",
             "Cathy Carden",
             "Cathy Guetta",
             "Cavallini",
             "Cb I Hate Perfumes",
             "Celine",
             "Celine Dion",
             "Cerruti",
             "Cesare Paciotti",
             "Chabaud Maison de Parfum",
             "Chabrawichi",
             "Chanel",
             "Chantal Thomass",
             "Chantecaille",
             "Charles Jourdan",
             "Charles Of The Ritz",
             "Charriol",
             "Chaugan",
             "Chaumet",
             "Chiemsee",
             "Chkoudra",
             "Chloe",
             "Chopard",
             "Chris Adams",
             "Chris Collins",
             "Christian Audigier",
             "Christian Breton",
             "Christian Dior",
             "Christian Lacroix",
             "Christian Louboutin",
             "Christian Richard",
             "Christian Siriano",
             "Christina Aguilera",
             "Christine Darvin",
             "Ciel",
             "Cigno Nero",
             "Cindy C",
             "Cindy Crawford",
             "City Parfum",
             "Claire Commeau",
             "Clarins",
             "Clayeux",
             "Clean",
             "Clinique",
             "Clive Christian",
             "CnR Create",
             "Coach",
             "Cofinluxe",
             "Collistar",
             "Comma",
             "Comme Des Garcons",
             "Commodity",
             "Coquillete",
             "Corday",
             "Costes",
             "Costume National",
             "Coty",
             "Coudray",
             "Courreges",
             "Crabtree & Evelyn",
             "Creed",
             "Cres 1927",
             "Cuarzo The Circle",
             "Cuba",
             "Cupid Perfumes",
             "Custo Barcelona",
             "Czech & Speake",
             "D'Elmar",
             "D'orsay",
             "D.S.&Durga",
             "Daddy Yankee",
             "Damien Bash",
             "Dana",
             "Daniel Josier",
             "Danielle Steel",
             "Darphin",
             "David Beckham",
             "David Jourquin",
             "David Thibaud-Bourahla",
             "David Yurman",
             "Davidoff",
             "De Ray",
             "Dear Diary",
             "Dear Rose",
             "Decleor",
             "Delarom",
             "Delta Parfum",
             "Demeter",
             "Denis Simachev",
             "Derek Lam 10 Crosby",
             "Desert",
             "Desigual",
             "Detaille",
             "Devota & Lomba",
             "Diadema Exclusif",
             "Diadora",
             "Diamyne",
             "Diana Ross",
             "Diana Vreeland",
             "Diane Pernet",
             "Diane Von Furstenberg",
             "Dianne Brill",
             "Diesel",
             "Dilis",
             "Dina",
             "Diptyque",
             "Disney",
             "Divage",
             "Divina Terra",
             "Divine",
             "Dolce & Gabbana",
             "Donna Karan",
             "Dora The Explorer",
             "Dorin",
             "Dorina",
             "Dr. Vranjes Firenze",
             "Dream Girlfriend",
             "Dsquared2",
             "Duccio Pasolini Parfums",
             "Dunhill",
             "Dupont",
             "Dusita",
             "Dynasty Of Monaco",
             "Dzintars",
             "E. Coudray",
             "Eau D`Italie",
             "Eclectic Collections",
             "Ed Hardy",
             "Eddie Barclay",
             "Edward Bess",
             "Egofacto",
             "Eight & Bob",
             "EL Charro",
             "Electimuss",
             "Elie Saab",
             "Elie Tahari",
             "Elisire",
             "Elite Model",
             "Elizabeth And James",
             "Elizabeth Arden",
             "Elizabeth Taylor",
             "Ella K",
             "Ella Mikao",
             "Ellen Tracy",
             "Elode",
             "Elysees Fashion",
             "Emanuel Ungaro",
             "Emeshel",
             "Emilio Pucci",
             "Emmanuel Levain",
             "Emor",
             "Emper",
             "Emporium",
             "English Laundry",
             "Enrico Coveri",
             "Enrico Gi",
             "Ermanno Scervino",
             "Erreuno",
             "Escada",
             "Escentric Molecules",
             "Esme Rene",
             "Esprit",
             "Esprit de Versailles",
             "Esse Strikes The Notes",
             "Essentia Puglia",
             "Essential Parfums",
             "Esteban",
             "Estee Lauder",
             "Estevia",
             "Etat Libre D'orange",
             "Etro",
             "Eutopie",
             "Eva Longoria",
             "Evaflor",
             "Evody Parfums",
             "Ex Floribus Vinis",
             "Ex Nihilo",
             "Exte",
             "Extrait D'Atelier",
             "Exuma Parfums",
             "F1 Parfums",
             "Fabi",
             "Faconnable",
             "Faith Hill",
             "Familia",
             "Fcuk",
             "Fee",
             "Fendi",
             "Ferrari",
             "Ferre",
             "Fiele Fragrances",
             "Fila",
             "Filippo Sorcinelli",
             "Fiorucci",
             "Flirt!",
             "Floraiku",
             "Florena Kolnisch",
             "Floris",
             "Fly Falcon",
             "FO'AH",
             "Forever Oud",
             "Fouquet's Parfum",
             "Fragonard",
             "Fragrance World",
             "France Papoo",
             "Francesca Bianchi",
             "Francesca Dell'Oro",
             "Francesco Smalto",
             "Franck Boclet",
             "Franck Muller",
             "Franck Olivier",
             "Francois Fournier",
             "Frankie Morello",
             "Frapin",
             "Fred Hayman",
             "Frederic Malle",
             "Fresh",
             "Fresh Line",
             "Fueguia 1833",
             "Furla",
             "Fwd",
             "Gabriela Sabatini",
             "Gabriele Strehle",
             "Gabriella Antosh",
             "Gai Mattiolo",
             "Gale Hayman",
             "Galerie Des Sens",
             "Galimard",
             "Gallivant",
             "Gandini 1896",
             "Gap",
             "Gattinoni",
             "Gendarme",
             "Genny",
             "Genty",
             "Genyum",
             "Geoffrey Beene",
             "George Gina & Lucy",
             "George Kordani",
             "Georges Rech",
             "Georges Stahl",
             "Geparlys",
             "Gerani",
             "Gerini",
             "Germain Monteil",
             "Gerry Weber",
             "Ghost",
             "Ghuroob",
             "Gian Marco Venturi",
             "Giardino Benessere",
             "Gilles Cantuel",
             "Gilly Hicks",
             "Ginestet",
             "Giorgio Armani",
             "Giorgio Beverly Hills",
             "Giorgio Monti",
             "Girinovsky",
             "Giulietta Capuleti",
             "Givenchy",
             "Glenn Perri",
             "Gloria Vanderbilt",
             "Goldfield & Banks Australia",
             "Goti",
             "Graff",
             "Graham & Pott",
             "Grandiflora",
             "Gres",
             "Greta Mastroianni",
             "Gri Gri Parfums",
             "Gritti",
             "Grossmith",
             "Gucci",
             "Guepard",
             "Guerlain",
             "Guess",
             "Guru Perfumes",
             "Gustave Eiffel",
             "Guy Laroche",
             "Gwen Stefani",
             "H2O Plus",
             "Halle Berry",
             "Halston",
             "Hamidi Oud&Perfumes",
             "Hanae Mori",
             "Hanorah",
             "Haute Fragrance Company",
             "Hayari Parfums",
             "Heeley",
             "Helena Rubinstein",
             "Helmut Lang",
             "Henri Bendel",
             "Henry Dunay",
             "Hermes",
             "Hermetica",
             "Herr von Eden",
             "Herve Gambs",
             "Herve Leger",
             "Hillari Duff",
             "Hind",
             "Hiroko Koshino",
             "Histoires De Parfums",
             "Hollister",
             "Homo Elegans",
             "Honore Des Pres",
             "Horseball",
             "Houbigant",
             "House Of Sillage",
             "HSK Paris",
             "Hubert Maes Creations",
             "Hugo Boss",
             "Humiecki & Graef",
             "Hunca",
             "Ibdaa",
             "Iceberg",
             "Ideo Parfumeurs",
             "Ikks",
             "Il Profumo",
             "Illuminum",
             "Ineke",
             "Ines de la Fressange",
             "Initio",
             "Instagirls",
             "Intesa",
             "Iris De Perla",
             "Isa",
             "Isaac Mizrahi",
             "Isabell",
             "Isabella Rosselini",
             "Isabelle T",
             "Isabey",
             "Isadora",
             "Issey Miyake",
             "Iunx Parfums",
             "Ivanka Tramp",
             "J. Casanova",
             "J. Del Pozo",
             "J.U.S",
             "Jackie Collins",
             "Jacomo",
             "Jacques Fath",
             "Jacques Zolty",
             "Jaeger",
             "Jaguar",
             "James Bond",
             "Jardin De France",
             "Jardin de Parfums",
             "Jardins d’Ecrivains",
             "Jason Wu",
             "Jasper Conran",
             "Jean Antoine",
             "Jean Batist",
             "Jean Charles Brosseau",
             "Jean Couturier",
             "Jean Desprez",
             "Jean Desses",
             "Jean Luc Amsler",
             "Jean Patou",
             "Jean Paul Gaultier",
             "Jean Reno",
             "Jean-Louis Scherrer",
             "Jean-Marc Sinan",
             "Jean-Michel Duriez",
             "Jeanne Arthes",
             "Jennifer Aniston",
             "Jennifer Lopez",
             "Jenny Glow",
             "Jeroboam",
             "Jessica Mcclintock",
             "Jessica Simpson",
             "Jessie Daniels",
             "Jil Sander",
             "Jimmy Choo",
             "Jin Abe Parfums",
             "Jivago",
             "JLS",
             "Jo Malone",
             "Jo Milano",
             "Joaquin Cortes",
             "Jockey",
             "Joe Sorrento",
             "Johan B",
             "John Galliano",
             "John Richmond",
             "John Varvatos",
             "Jones New York",
             "Joop!",
             "Jordin Sparks",
             "Jose Eisenberg",
             "Joseph",
             "Jouany Perfumes",
             "Jovan",
             "Jovoy Paris",
             "Judith Leiber",
             "Juicy Couture",
             "Jul Et Mad",
             "Juliette Has A Gun",
             "Jusbox",
             "Just Hookah",
             "Just Jack",
             "Justin Bieber",
             "Juvena Sarabe",
             "Kajal",
             "Kaloo",
             "Kanebo",
             "Karen Low",
             "Karl Antony",
             "Kat Von D",
             "Kate Moss",
             "Kate Spade",
             "Kathy Hilton",
             "Katy Perry",
             "Kayali",
             "Keiko Mecheri",
             "Kemi Blending Magic",
             "Kenji Tanaka",
             "Kenneth Cole",
             "Kensie",
             "Kenzo",
             "Kesma",
             "Khalis",
             "Khaltat",
             "Khloe And Lamar",
             "Kiehl`s",
             "Kilian",
             "Kim Kardashian",
             "Kimmi Fragrance",
             "Kimora Lee Simmons",
             "Kiton",
             "Knize",
             "Kokeshi",
             "Kolmaz",
             "Kookai",
             "Korloff",
             "Korres",
             "Koto Parfums",
             "Koutisse",
             "KPK Parfum",
             "Kristel Saint Martin",
             "Krizia",
             "Kusado",
             "Kylie Minogue",
             "L'Arc",
             "L'Artisan Parfumeur",
             "L'Atelier Boheme",
             "L'occitane",
             "L.t. Piver",
             "La Collina Toscana",
             "La Cristallerie des Parfums",
             "La Maison de la Vanille",
             "La Manufacture",
             "La Martina",
             "La Perla",
             "La Prairie",
             "La Sultane",
             "Labeau",
             "Laboratorio Olfattivo",
             "Laboratory Perfumes",
             "Lacoste",
             "Lady Gaga",
             "Lagerfeld",
             "Lalique",
             "Lancaster",
             "Lancetti",
             "Lancome",
             "Lanvin",
             "Lattafa Perfumes",
             "Laura Ashley",
             "Laura Biagiotti",
             "Laura Mercier",
             "Laura Tonatto",
             "Laurelle",
             "Le Cercle des Parfumeurs Createurs",
             "Le Couvent Maison De Parfum",
             "Le Galion",
             "Le Labo",
             "Le Monarque",
             "Le Parfum D'interdits",
             "Le Parfumeur",
             "Le Prince Jardinier",
             "Lee Cooper",
             "Legendary Fragrances",
             "Lengling",
             "Lentheric",
             "Leonard",
             "Les Aphrodisiaques",
             "Les Cocottes de Paris",
             "Les Contes",
             "Les Copains",
             "Les Destinations",
             "Les EAUX Primordiales",
             "Les Fleurs De Bach",
             "Les Liquides Imaginaires",
             "Les Nereides",
             "Les Parfums De Rosine",
             "Les Parfums Suspendus",
             "Les Soeurs De Noe",
             "Linari",
             "Lindo Ganarin",
             "Linea De Bella",
             "Linn Young",
             "Liquid Money",
             "Liquides Imaginaires",
             "Lise Watier",
             "Litoralle Aromatica",
             "Liu Jo",
             "Liz Claiborne",
             "LM Parfums",
             "Lobogal",
             "Loewe",
             "Loft Design By",
             "Lolita Lempicka",
             "Lomani",
             "Lonkoom",
             "Loree Rodkin",
             "Lorelyane",
             "Lorenzo Villoresi",
             "Lostmarch",
             "Lotto",
             "Louis Feraud",
             "Louis Vuitton",
             "Love Passport",
             "Love The Key To Life",
             "Lubin",
             "Luciano Pavarotti",
             "Luciano Soprani",
             "Lucien Ferrero Maitre Parfumeur",
             "Lucky",
             "Lui Niche",
             "Luigi Borrelli",
             "Lulu Castagnette",
             "Lulu Guinness",
             "Luxury Concept",
             "M.INT",
             "MAC",
             "Mad Et Len",
             "Madeleine Vionnet",
             "Madison",
             "Madonna",
             "Magruss Paola",
             "Maison Crivelli",
             "Maison Francis Kurkdjian",
             "Maison Gabriella Chieffo",
             "Maison Martin Margiela's",
             "Maison Rebatchi",
             "Maison Tahite",
             "Maitre Parfumeur Et Gantier",
             "Majda Bekkali",
             "Maje",
             "Making of Cannes",
             "Mancera",
             "Mandarina Duck",
             "Maori Collection",
             "Map Of The Heart",
             "Marbert",
             "Marc de la Morandiere",
             "Marc Jacobs",
             "Marc Joseph",
             "Marc O'polo",
             "Marc Rosen",
             "Marc-Antoine Barrois",
             "Marcella Wouters",
             "Maria Candida",
             "Maria Sharapova",
             "Mariah Carey",
             "MariaLux",
             "Marie Jeanne",
             "Mariella Burani",
             "Marilyn Miglin",
             "Marilyn Monroe",
             "Marina De Bourbon",
             "Marina Marinof",
             "Marina Picasso",
             "Marina Spadafora",
             "Marina Yachting",
             "Mark Buxton",
             "Marly",
             "Marni",
             "Marshall Field's",
             "Mary-Kate And Ashley Olsen",
             "Maryaj",
             "Masaki Matsushima",
             "Masque Milano",
             "Massimo Dutti",
             "Matiere Premiere",
             "Matthew Williamson",
             "Mawaz Manzor",
             "Max Azria",
             "Max Deville",
             "Max Mara",
             "Max Philip",
             "Maxim's De Paris",
             "May Fair Le Caire",
             "Mazzolari",
             "Mdci Parfums",
             "Medical Beauty Research",
             "Mekkanische Rose",
             "Memento",
             "Memo",
             "Menard",
             "Mendittorosa",
             "Meo Fusciuni",
             "Mercedes Benz",
             "Merhis Perfumes",
             "Mexx",
             "Micaelangelo",
             "Micallef",
             "Michael Jackson",
             "Michael Kors",
             "Michel Germain",
             "Michel Klein",
             "Michel Swiss",
             "Michele Bianchi",
             "Mick Micheyl",
             "Mila Schon",
             "Milano Fragranze",
             "Miller Et Bertaux",
             "Miller Harris",
             "Mimmina",
             "Min New York",
             "Miraculum",
             "Mirko Buffini",
             "Misk",
             "Miss Corolle",
             "Miss Sixty",
             "Missoni",
             "Mistral",
             "Miu Miu",
             "Mizensir",
             "Mode Creation Munich",
             "Mojo",
             "Molinard",
             "Molsheim & Co",
             "Molton Brown",
             "Molyneux",
             "Mona di Orio",
             "Monart Parfums",
             "Monet's Palette",
             "Monotheme",
             "Mont Blanc",
             "Montale",
             "Montana",
             "Montegrappa",
             "Morabito",
             "Moresque",
             "Morgan",
             "Morgane Le Fay",
             "Morris",
             "Moschino",
             "MPF",
             "Mullium",
             "Museum Parfums",
             "Music De Parfum",
             "Must-Have",
             "My Perfumes",
             "Myrurgia",
             "Nabeel",
             "Naf Naf",
             "Naj-oleari",
             "Nanette Lepore",
             "Naomi Campbell",
             "Naomi Goodsir",
             "Narciso Rodriguez",
             "Naso Di Raza",
             "Nasomatto",
             "Natori",
             "Nautica",
             "Nautilus",
             "Nayassia",
             "Nazareno Gabrielli",
             "Neela Vermeire Creations",
             "Nejma",
             "NellyRodi",
             "Neotantric Fragrances",
             "Nest",
             "New Brand",
             "New York Yankees",
             "New Yorker",
             "Nez A Nez",
             "Nickel",
             "Nicki Minaj",
             "Nicolai Parfumeur Createur",
             "Nicolas Danila",
             "Nicole",
             "Nicole Farhi",
             "Nicole Miller",
             "Nicole Richie",
             "Niki de Saint Phalle",
             "Nikos",
             "Nina Ricci",
             "Nine West",
             "Nishane",
             "Nobile 1942",
             "Noble Royale",
             "Nomenclature",
             "Norana Perfumes",
             "Nouveau Paris",
             "Novae Plus",
             "Nu Be",
             "Nuage",
             "Nvdo",
             "O.J Perrin",
             "Obvious",
             "Ocean Pacific",
             "Odejo",
             "Odin",
             "Odori",
             "Officina Delle Essenze",
             "Ojar",
             "Okki",
             "Oksana Robski",
             "Olfactive Studio",
             "Olfattology",
             "Olibere Parfums",
             "Olivier Durbano",
             "Olivier Strelli",
             "Omar Sharif",
             "Omnia Profumi",
             "One Direction",
             "Onyrico",
             "Orchid Perfumes",
             "Orens Parfums",
             "Oriflame",
             "Oriza L. Legrand",
             "Orlane",
             "Orlov Paris",
             "Ormonde Jayne",
             "Oros",
             "Orto Parisi",
             "Oscar De La Renta",
             "Otto Kern",
             "Oudh Al Anfar",
             "Paco Rabanne",
             "Pacoma",
             "Pacoroca",
             "Paglieri",
             "Pal Zileri",
             "Paloma Picasso",
             "Pamela Anderson",
             "Panama 1924",
             "Pancaldi & B",
             "Pani Walewska",
             "Panier",
             "Panouge",
             "Pantheon Roma",
             "Paola Ferri",
             "Paolo Gigli",
             "Paolo Pecora Milano",
             "Paper Passion",
             "Parabole",
             "Parah",
             "Parfico",
             "Parfum Blaze",
             "Parfum Collection",
             "Parfum d'Empire",
             "Parfum De Sevigne",
             "Parfum Hashtag",
             "Parfume De Vanille",
             "Parfumerie Generale",
             "Parfumerie Particuliere",
             "Parfums 137",
             "Parfums BDK",
             "Parfums Berdoues",
             "Parfums Bombay 1950",
             "Parfums Ciro",
             "Parfums De La Bastide",
             "Parfums de Marly",
             "Parfums DelRae",
             "Parfums du Chateau de Versailles",
             "Parfums et Senteurs du Pays Basque",
             "Parfums Lively",
             "Parfums Regine",
             "Parfums Sophiste",
             "Paris Bleu Parfums",
             "Paris Hilton",
             "Paris World Luxury",
             "Parle Moi de Parfum",
             "Parour",
             "Pascal Morabito",
             "Pascal Schaller",
             "Patrice Martin",
             "Patrik Mauboussin",
             "Patrizia Pepe",
             "Paul & Joe",
             "Paul Emilien",
             "Paul Sebastian",
             "Paul Smith",
             "Paulina Rubio",
             "Payot",
             "Pedro Del Hierro",
             "Penhaligon's",
             "Penthouse",
             "Pepe Jeans",
             "Perfect Sense Mane",
             "Perfume Jewels",
             "Perfume Ny Gear Inc",
             "Perfumer's Workshop",
             "Perfumeria Gal",
             "Perris",
             "Perry Ellis",
             "PH Fragrances",
             "Phaedon",
             "Pharrell Williams",
             "Philippe Venet",
             "Philly&Phill",
             "Philosophy",
             "Phuong Dang",
             "Pierre Balmain",
             "Pierre Cardin",
             "Pierre Guillaume",
             "Pierre Precieuse",
             "Pierre Wulff",
             "Pineider",
             "Pitbull",
             "Playboy",
             "Plume Impression",
             "Poiray",
             "Pola",
             "Police",
             "Pomellato",
             "Ponti Parfum",
             "Popy Moreni",
             "Porcci",
             "Porsche Design",
             "Positive Parfum",
             "Powell`s",
             "Prada",
             "Premier",
             "Prescriptives",
             "Prima Materia",
             "Prince",
             "Prince Henri D'Orleans",
             "Prince Matchabelli",
             "Priscilla Presley",
             "Prism Parfums",
             "Profumi del Forte",
             "Profumi di Pantelleria",
             "Profumo Di Firenze",
             "Profumum Roma",
             "Prudence Paris",
             "Puccini",
             "Puma",
             "Puredistance",
             "Queen B",
             "Queen Latifah",
             "Quiksilver",
             "Rahla",
             "Rallet",
             "Ralph Lauren",
             "Ramon Bejar",
             "Ramon Molvizar",
             "Ramon Monegal",
             "Rampage",
             "Rance",
             "Rania J",
             "Rasasi",
             "Raymond Matts",
             "Re Profumo",
             "Realm",
             "Reem Acra",
             "Regalien",
             "Reminiscence",
             "Remy Latour",
             "Remy Marquis",
             "Ren",
             "Renato Balestra",
             "Rene Amber",
             "Rene Lezard",
             "Rene Solange",
             "Renee",
             "Renegades",
             "Repetto",
             "Replay",
             "Revelations Perfumes",
             "Revillon",
             "Revlon",
             "Reyane",
             "Richard James",
             "Rifat Ozbek",
             "Rihanna",
             "Rituals",
             "Roads",
             "Robert Beaulieu",
             "Robert Piguet",
             "Roberto Capucci",
             "Roberto Cavalli",
             "Roberto Verino",
             "Robski & Sobchac",
             "Roccobarocco",
             "Rochas",
             "Rodier",
             "Roger & Gallet",
             "Roja Dove",
             "Romea D`ameor",
             "Romeo Gigli",
             "Ron Robinson",
             "Room 1015",
             "Roos & Roos",
             "Rose & Co Manchester",
             "Rosendo Mateu Olfactive Expressions",
             "Rouge Bunny Rouge",
             "Royal Crown",
             "Royal Doulton",
             "Royal Monceau",
             "Rsw",
             "Rubeus Milano",
             "Rubino Cosmetics",
             "Ruth Mastenbroek",
             "S-Perfume",
             "S.Ishira",
             "S.oliver",
             "S4P",
             "Sahlini",
             "Saint James",
             "Saledo",
             "Salle Privee",
             "Salvador Dali",
             "Salvatore Ferragamo",
             "Sandalia",
             "Sandro",
             "Santa Eulalia",
             "Santa Maria Novella",
             "Santi Burgas",
             "Sarah Connor",
             "Sarah Jessica Parker",
             "Sarantis",
             "Scent Bar",
             "ScentStory",
             "Schiaparelli",
             "Schwarzlose Berlin",
             "Sean John",
             "Selena Gomez",
             "Sensai",
             "Sephora",
             "Serge Dumonten",
             "Serge Louis Alvarez",
             "Serge Lutens",
             "Serge Normant",
             "Sergio Nero",
             "Sergio Tacchini",
             "SG79 STHLM",
             "Shaik",
             "Shakira",
             "Shanghai",
             "Shawn Mendes",
             "Shay&Blue London",
             "Shiseido",
             "Siberian Wellness",
             "Signature",
             "Signature Fragrances",
             "Simimi",
             "Simone Andreoli",
             "Simone Cosac Profumi",
             "Sir Parfumer",
             "Sisley",
             "Six Scents",
             "Slava Zaitsev",
             "Slazenger",
             "Smile Paris",
             "Snap",
             "Snoopy Fragrance",
             "Sofia Vergara",
             "Solange",
             "Solinotes",
             "Sonia Rykiel",
             "Sooud",
             "Sorelle Fontana",
             "Sospiro Perfumes",
             "Spada",
             "Spirit Of Kings",
             "SpongeBob Squarepants",
             "Stacked Style",
             "Starck",
             "State of Mind",
             "Stefano Canturi",
             "Stefano Ricci",
             "Stella Cadente",
             "Stella Mccartney",
             "Stendhal",
             "Stephane Humbert Lucas 777",
             "Stephanie De Bruijn",
             "Sterling Parfums",
             "Succes de Paris",
             "Sud Pacifique",
             "Sue Wong",
             "Superdry",
             "Susan G. Komen For The Cure",
             "Susanne Lang",
             "Swarovski",
             "SweDoft",
             "Sweet Years",
             "Swiss Arabian",
             "Swiss Guard",
             "Syed Junaid",
             "Sylvaine Delacourte",
             "Tableau De Parfums",
             "Talismans Collezione Preziosa",
             "Tan Giudicelli",
             "Tann Rokka",
             "Tauer Perfumes",
             "Tauerville",
             "Tauleto",
             "Taylor Swift",
             "Teatro Fragranze Uniche",
             "Ted Baker",
             "Ted Lapidus",
             "Teo Cabanel",
             "Tequila",
             "Teresa Helbig",
             "Terry de Gunzburg",
             "Thameen",
             "The Body Shop",
             "The Different Company",
             "The Fragrance Kitchen",
             "The Gate",
             "The Grand Budapest Hotel",
             "The Harmonist",
             "The House of Oud",
             "The Hype Noses",
             "The Merchant of Venice",
             "The Parfum",
             "The Party",
             "The People Of The Labyrinths",
             "The Smurfs",
             "The Spirit Of Dubai",
             "The Vagabond Prince",
             "The Woods Collection",
             "Theo Fennell",
             "Thierry Mugler",
             "Thirdman",
             "Thomas Kosmala",
             "Tiffany",
             "Tiziana Terenzi",
             "Tocca",
             "Todd Oldham",
             "Tom Daxon",
             "Tom Ford",
             "Tom Tailor",
             "Tommi Sooni",
             "Tommy Bahama",
             "Tommy Hilfiger",
             "Tonino Lamborghini",
             "TOPModel",
             "Torrente",
             "Tory Burch",
             "Tous",
             "Trish Mcevoy",
             "True Brit London",
             "True Religion",
             "Trussardi",
             "Tuiga",
             "U.s.polo",
             "UER MI",
             "Ulric de Varens",
             "Umbro",
             "Undergreen",
             "Une Nuit Nomade",
             "Unice",
             "Unique Parfum",
             "Unum",
             "Usher",
             "V Canto",
             "Valentin Yudashkin",
             "Valentina By Guido Crepax",
             "Valentino",
             "Valmont",
             "Van Cleef & Arpels",
             "Van Gils",
             "Vendara",
             "Venice Beach",
             "Vera Wang",
             "Verduu",
             "Vero Profumo",
             "Veronique Gabai",
             "Versace",
             "Vertigo Parfums",
             "Vertus",
             "Vicini",
             "Vicky Tiel",
             "Victor Manuelle",
             "Victoria's Secret",
             "Victorinox Swiss Army",
             "Victorio & Lucchino",
             "Viktor & Rolf",
             "Vilhelm Parfumerie",
             "Vince Camuto",
             "Vivant",
             "Vive Maria",
             "Vivienne Sabo",
             "Vivienne Westwood",
             "Votre Parfum",
             "Voyages Imaginaires",
             "Vurv",
             "Waterford",
             "Weil",
             "Welton",
             "Western Valley Avenue",
             "Whatever It Takes",
             "Wide Society",
             "Women'secret",
             "Worth",
             "Xerjoff",
             "Xoxo",
             "Yardley",
             "YesForLov",
             "Yllozure",
             "Yohji Yamamoto",
             "Ys-Uzac",
             "Yvan & Marzia",
             "Yves De Sistelle",
             "Yves Saint Laurent",
             "Zadig & Voltaire",
             "Zarah Scents",
             "Zarkoperfume",
             "Zeenat Aman",
             "Zeromolecole",
             "Zielinski & Rozen",
             "Zippo",
             "Zlatan Ibrahimovic Parfums",
             "10 Corso Como",
             "1000 Flowers",
             "12 Parfumeurs Francais",
             "19-69",
             "20th Century Fox",
             "24",
             "27 87",
             "4160 Tuesdays",
             "4711",
             "Аберкромби и Фитч",
             "Абсолюмент Парфюмер",
             "Акка Каппа",
             "Ачендис",
             "Аква дел Элба",
             "Аква Дел Ланге",
             "Аква Ди Бьелла",
             "Аква ди Дженова",
             "Аква ди Монако",
             "Аква Ди Парма",
             "Аква Ди Портофино",
             "Аква ди Сардегна",
             "Аква ди Стреза",
             "Аква Реале",
             "Адам Лавин",
             "Адидас",
             "Адольфо Домингес",
             "Адриани Виттадини",
             "Айдес де Венустас",
             "Аффинэссэнс",
             "Афнен",
             "Агата Руис Де Ла Прада",
             "Агато Парфюм",
             "Агент Провокатор",
             "Агнес Би",
             "Агонист",
             "Ахжар",
             "Айгнер",
             "Аж Арабиа",
             "Аджмал",
             "Ак Франсе",
             "Акро",
             "Аль Хаматт",
             "Аль Харамейн",
             "Аль Маржаан",
             "Алайа",
             "Ален Арегон",
             "Ален Делон",
             "Алан Брай",
             "Альберт Нипон",
             "Альберта Ферретти",
             "Альбэн Дю Рой",
             "Алессандро Дел Аква",
             "Александро Делла Торе",
             "Алекс Симон",
             "Алекса Ликсфилд",
             "Александр Маквин",
             "Александр Джи",
             "Альфред Санг",
             "Альгабра Парфюмс",
             "Алла Пугачева",
             "Альтро арОма",
             "Альвиеро Мартини",
             "Алисса Эшли",
             "Американ Игл",
             "Аморино Прайв",
             "Амуаж",
             "Амороуд",
             "Амвей",
             "Анат Фриц",
             "Андре Аршер",
             "Андреа Маак",
             "Анре Путман",
             "Анфас Aлхалеей Перфюмс",
             "Анж Лапин",
             "Ангел Шлессер",
             "Анжела Чампаньа",
             "Анима Мунди",
             "Анна Пагера",
             "Анна Суи",
             "Аннаяке",
             "Анна Фонтане",
             "Анна Кляйн",
             "Анник Гуталь",
             "Антониа Флауэрс",
             "Антонио Алессандриа",
             "Антонио Бандерас",
             "Антонио Фуско",
             "Антонио Пьюиг",
             "Антонио Висконти",
             "Ануччи",
             "Аквалина",
             "Арабеск",
             "Арабиан Уд",
             "Арамис",
             "Ард Аль Заафаран",
             "Ариана Гранде",
             "Армаф",
             "Арманд Баси",
             "Армориаль",
             "Арно Сорель",
             "Арроганс",
             "Атре Профюми",
             "АртеОльфатто",
             "Асаэл",
             "Ашгарали",
             "Ателье Колонь",
             "Ательер де Орс",
             "Ательер Флоу",
             "Ателье Матэри",
             "Аткинсонс",
             "Аттар Коллекшн",
             "Аврил Лавин",
             "Аксис",
             "Азагури",
             "Аззаро",
             "Аш 2 О Плюс",
             "Айсберг",
             "Амбро",
             "Андергрин",
             "Ашер",
             "Алые Паруса",
             "Би Эн Би Косметикс",
             "Би Прайм Парфюм",
             "Би Ю",
             "Бэдли Мишка",
             "Балди",
             "Балдинини",
             "Баленсиага",
             "Бамотте",
             "Банана Репаблик",
             "Барби",
             "Барниз Нью-Йорк",
             "Бас Энд Боди Уоркс",
             "БьюФорт Ландон",
             "Бебе",
             "Бежар",
             "Беллеганс",
             "Бенефит",
             "Бенеттон",
             "Бернд Бергер",
             "Бесо Бич Перфюмс",
             "Бетси Джонсон",
             "Бетти Барклай",
             "Бетти Буп",
             "Бейонсе",
             "Бхарара Бьюти",
             "Биэль",
             "Биджан",
             "Билл Бласс",
             "Биотерм",
             "Бьорк Энд Берриз",
             "Блэкглама",
             "Бленд Уд",
             "Блисс Перфюмс",
             "Блуд Концепт",
             "Блюмарин",
             "Боадицея зе Викториус",
             "Боб Маки",
             "Бобби Браун",
             "Богарт",
             "Богнер",
             "Боис 1920",
             "Бонд 9",
             "Боржез",
             "Борсалино",
             "Борсари",
             "Ботаника Экспрешнс",
             "Боттега Профюмьера",
             "Боттега Венета",
             "Бушерон",
             "Буж",
             "Боржуа",
             "Брачиалини",
             "Брекурт",
             "Брейн Милано",
             "Бритни Спирс",
             "Брокард",
             "Брукс Бразерс",
             "Брюс Олдфилд",
             "Бруно Банани",
             "Брут",
             "Би Эс Ку",
             "Барбери",
             "Бардин",
             "Баттерфляй",
             "Булгари",
             "Библос",
             "БайБозо",
             "Байредо Парфюмс",
             "Бердуи",
             "Ван Дирекшн",
             "Версальс",
             "В Канто",
             "Валентин Юдашкин",
             "Валентина Бай Гвидо Крепакс",
             "Валентино",
             "Вальмон",
             "Ван Клиф",
             "Ван Гилс",
             "Вендара",
             "Венис Бич",
             "Вера Вонг",
             "Верду",
             "Веро Профумо",
             "Вероник Габай",
             "Версаче",
             "Вертиго Парфамс",
             "Вертус",
             "Висини",
             "Вики Тиль",
             "Виктор Мануэль",
             "Виктория Сикрет",
             "Викторинокс Свисс Армии",
             "Викторио и Лучино",
             "Виктор и Рольф",
             "Вильхельм Парфюмери",
             "Венче Камуто",
             "Вивант",
             "Вив Мария",
             "Вивьен Сабо",
             "Вивьен Вествуд",
             "Вотре Парфам",
             "Вояжес Имажине",
             "Вюрв",
             "Вэйл",
             "Велтон",
             "Вестерн Вэлли Авеню",
             "ВотЭвер Ит Тэйкс	",
             "Вайд Сэсаети",
             "Вумен Сикрет",
             "Ворх",
             "Габриэль Сабатини",
             "Габриэла Штреле",
             "Габриэлла Антош",
             "Гай Матиоло",
             "Гейл Хейман",
             "Галери Дес Сенс",
             "Галимард",
             "Галливант",
             "Гандини 1896",
             "Гэп",
             "Гаттинони",
             "Гениум",
             "Гепарлис",
             "Герани",
             "Герини",
             "Гост",
             "Гуруб",
             "Гленн Перри",
             "Глория Вандербильт",
             "Голдфилд и Бэнкс Австралия",
             "Готи",
             "Графф",
             "Грэм и Потт",
             "Грандифлора",
             "Грес",
             "Грета Мастрояни",
             "Гри Гри Парфюмс",
             "Гритти",
             "Гроссмит",
             "Гуччи",
             "Гепард",
             "Герлен",
             "Гэсс",
             "Гуру Перфюмс",
             "Густав Эйфель",
             "Гай Ларош",
             "Гвен Стефани",
             "Генри Бендель",
             "Генри Дюней",
             "Гермес",
             "Гомо Элеганс",
             "Дельмар",
             "Д'орсей",
             "Д.С. и Дурга",
             "Дэдди Янки",
             "Дамьен Баш",
             "Дана",
             "Даниэль Джозьер",
             "Даниэль Стил",
             "Дарфан",
             "Дэвид Бэкхем",
             "Дэвид Дженкинс",
             "Дэвид Тибо-Бурала",
             "Дэвид Юрман",
             "Давидофф",
             "Дэ Рэй",
             "Диа Дайри",
             "Диа Розе",
             "Деклеор",
             "Деларом",
             "Дельта Парфюм",
             "Дэметр",
             "Денис Симачев",
             "Дерек Лэм 10 Кросби",
             "Дезерт",
             "Десигвал",
             "Детэйл",
             "Девота и Ломба",
             "Диадема Эксклюзив",
             "Диадора",
             "Диамин",
             "Диана Росс",
             "Диана Вриланд",
             "Дианэ Пэрнэт",
             "Диан",
             "Диана Брилл",
             "Дизель",
             "Дилис",
             "Дина",
             "Диптик",
             "Дисней",
             "Диваж",
             "Дивина Тэрра",
             "Дивайн",
             "Дольче и Габбана",
             "Донна Каран",
             "Дора Зэ Эксплорер",
             "Дорин",
             "Дорина",
             "Доктор Враньес Фиренце",
             "Дрим Гёрлфренд",
             "Дискваред2",
             "Дуччо Пазолини Парфюмс",
             "Данхилл",
             "Дюпон",
             "Дусита",
             "Династи оф Монако",
             "Дзинтарс",
             "Дженни",
             "Джентли",
             "Джордж Джина энд Люси",
             "Джордж Кордани",
             "Джорджес Стал",
             "Джерри Вебер",
             "Джардино Бенессере",
             "Джилли Хикс",
             "Джинестет",
             "Джоржио Армани",
             "Джорджио Беверли Хиллз",
             "Джорджио Монти",
             "Джульетта Капулетти",
             "Джэй Казанова",
             "Джей Дэл Позо",
             "Джей. Ю. Эс",
             "Джеки Коллинз",
             "Джеймс Бонд",
             "Джейсон Ву",
             "Джаспер Конран",
             "Джон Энтони",
             "Дженнифер Энистон",
             "Дженифер Лопез",
             "Дженни Глоу",
             "Джэробоам",
             "Джессика МакКлинток",
             "Джессика Симпсон",
             "Джесси Даниэль",
             "Джил Сандер",
             "Джимми Чу",
             "Джин Абе",
             "Джэй Эл Эс",
             "Джо Малон",
             "Джо Милано",
             "Джоки",
             "Джо Соренто",
             "Джон Гальяно",
             "Джон Ричмонд",
             "Джон Варватос",
             "Джонс Нью-Йорк",
             "Джуп!",
             "Джордин Спаркс",
             "Джозеф",
             "Джуани Парфюмс",
             "Джовой Пари",
             "Джудит Лейбер",
             "Джуси Кутюр",
             "Джульетта с пистолетом",
             "Джусбокс",
             "Джаст Хука",
             "Джаст Джэк",
             "Джастин Бибер",
             "Джавена Сараб",
             "Дифферент Компани",
             "Е. Коудри",
             "Ерманно Шервино",
             "Ева Лонгория",
             "Егерь",
             "ЕсФоЛов",
             "Жандарм",
             "Жофри Бин",
             "Жорж Реч",
             "Жермен Монте",
             "Жан Марко Вентури",
             "Жиль Кантюэль",
             "Жириновский",
             "Живанши",
             "Жакомо",
             "Жак Фат",
             "Жак Золти",
             "Жардан Дю Франс",
             "Жардан Дю Парфамс",
             "Жардан Д Экриванс",
             "Жан Батист",
             "Жан Шарлес Броссо",
             "Жан Кутюрье",
             "Жан Деспрез",
             "Жан Дессес",
             "Жан Люк Амслер",
             "Жан Пату",
             "Жан Поль Готье",
             "Жан Рено",
             "Жан Луи Шеррер",
             "Жан-Мишель Дюрье",
             "Живаго",
             "Жакин Кортес",
             "Жос Эйзенберг",
             "Жул ет Мэд",
             "Зэ Бади Шоп",
             "Зе Фрагранс Китчен",
             "Зе Гейт",
             "Зэ Гранд Будапешт Хотэл",
             "Зэ Хармонист",
             "Зе Хаус Уд",
             "Зэ Хайп Ноузез",
             "Зе Мерчант оф Венеция",
             "Зэ Парфюм",
             "Зэ Пати",
             "Зэ Спирит Оф Дубай",
             "Зе Вагабонд Принц",
             "Зе Вуд Коллекшн",
             "Задиг и Вольтер",
             "Зара Сэнтс",
             "Заркоперфюм",
             "Зинат Аман",
             "Зеромолекол",
             "Зелински и Розен",
             "Зиппо",
             "Златан Ибрагимович Парфюмс",
             "Инглиш Лондри",
             "Ибда",
             "Идео Парфюмерс",
             "Икс",
             "Иль Профумо",
             "Иллюминум",
             "Инеке",
             "Инес де ла Фрессанж",
             "Инишио",
             "Инстагёлз",
             "Интеса",
             "Ирис Дэ Перла",
             "Иса",
             "Исаак Мизрахи",
             "Изабель",
             "Изабелла Росселини",
             "Изабель Ти",
             "Исабей",
             "Исадора",
             "Иссей Мияке",
             "Иванка Трамп",
             "Иллозур",
             "Иван и Марция",
             "Ив Де Систель",
             "Ив Сен Лоран",
             "Иверия",
             "Йохан Би",
             "Йован",
             "Йоджи Ямамото",
             "Кашарель",
             "Каесарс",
             "Кафе-Кафе",
             "Кале Фрагрансе Д'атур",
             "Каллиграфи",
             "Кэлвин Кляйн",
             "Каликс",
             "Кампос де Ибица",
             "Кардио Банни",
             "Карин Ройтфелд",
             "Карита",
             "Карла Фраччи",
             "Карлос Кампос",
             "Карлос Сантана",
             "Карнер Барселона",
             "Каролина Эррера",
             "Кэролин Мерфи",
             "Карон",
             "Карремент Бель",
             "Каррера",
             "Картузия",
             "Картье",
             "Карвен",
             "Кастельбажак",
             "Кэти Карден",
             "Кати Гюэтта",
             "Каваллини",
             "Кесар Пачиотти",
             "Кимзе",
             "Крис Адамс",
             "Крис Коллинз",
             "Кристиан Одижье",
             "Кристиан Бретон",
             "Кристиан Диор",
             "Кристиан Лакруа",
             "Кристиан Лабутен",
             "Кристиан Ричард",
             "Кристиан Сириано",
             "Кристина Агилера",
             "Кристин Дарвин",
             "Клэр Коммо",
             "Кларанс",
             "Клаукс",
             "Клин",
             "Клиник",
             "Клайв Кристиан",
             "Коуч",
             "Кофинлюкс",
             "Коллистар",
             "Комма",
             "Ком де Гарсон",
             "Комодити",
             "Кокулетте",
             "Кордэй",
             "Костес",
             "Костюм Националь",
             "Коти",
             "Кудрей",
             "Кураж",
             "Крэбтри Энд Эвелин",
             "Крид",
             "Крес 1927",
             "Куарзо зе Киркле",
             "Куба",
             "Купид Перфюмс",
             "Кусто",
             "Каджал",
             "Калу",
             "Канебо",
             "Карен Лоу",
             "Карл Энтони",
             "Кат Вон Д",
             "Кейт Мосс",
             "Кейт Спейд",
             "Кэтти Хилтон",
             "Кэти Перри",
             "Каяли",
             "Кейко Мечери",
             "Кеми Блэндинг Мэджик",
             "Кенджи Танака",
             "Кеннет Коул",
             "Кенси",
             "Кензо",
             "Кесма",
             "Кхалис",
             "Кхалтат",
             "Кихлс",
             "Килиан",
             "Ким Кардашян",
             "Кимми Фрагранс",
             "Кимора Ли Симмонс",
             "Китон",
             "Книзэ",
             "Кокеси",
             "Колмаз",
             "Кукаи",
             "Корлофф",
             "Коррес",
             "Кото Парфюмс",
             "Кутисс",
             "КПК Парфюм",
             "Кристел Сент Мартин",
             "Кризиа",
             "Кусадо",
             "Кайли Миноуг",
             "Куин Б",
             "Куин Латифа",
             "Квиксильвер",
             "Ксерджофф",
             "Линкс Парфюмс",
             "Ль Арс",
             "Ль Ательер Бохем",
             "Локситан",
             "Л.Т.Пивер",
             "Ля Коллина Тоскана",
             "Ля Кристали Дэ Парфам",
             "Ла Мэйсон Де Ла Ванилле Ванахи",
             "Ла Мануфактур",
             "Ла Мартина",
             "Ла Перла",
             "Ла Прери",
             "Ла Султан",
             "Лабо",
             "Лабораторио Олфативо",
             "Лаборатори Парфюмс",
             "Лакост",
             "Леди Гага",
             "Лагерфельд",
             "Лалик",
             "Ланкастер",
             "Ланцетти",
             "Ланком",
             "Ланвин",
             "Латтафа Перфюмс",
             "Лаура Эшли",
             "Лаура Биаджотти",
             "Лаура Мерсье",
             "Лаура Тонатто",
             "Лорель",
             "Лё Серкл Дэ Парфюмерс Криэтэрс",
             "Лю Кюво Майзон Дэ Парфам",
             "Ле Галион",
             "Ле Лабо",
             "Лю Монарк",
             "Ле Парфюм Д'интердитс",
             "Ле Парфюмер",
             "Ли Купер",
             "Лэджендэри Фрэгрэнсис",
             "Ленглинг",
             "Лентерик",
             "Леонард",
             "Лес Афродизиак",
             "Ле Кокот де Пари",
             "Лес Контес",
             "Лес Копейнс",
             "Ле Дистинасьон",
             "Ле Зу Примодиаль",
             "Ле Флёр Дю Бак",
             "Лё Ликид Имажинэ",
             "Ле Нерид",
             "Лес Парфюмс Де Росин",
             "Лес Парфамс Суспендус",
             "Ле Сёрс Дэ Ноэ",
             "Линари",
             "Линдо Ганарин",
             "Линеа Ди Бэлла",
             "Линн Янг",
             "Ликвид Мани",
             "Ликвидус Имаджинари",
             "Лис Вотиер",
             "Литоралле Ароматика",
             "Лиу Джо",
             "Лиз Клайборн",
             "Ларан Маззоне",
             "Лобогал",
             "Лоев",
             "Лолита Лемпика",
             "Ломани",
             "Лонкум",
             "Лори Родкин",
             "Лорлиан",
             "Лорензо Виллореси",
             "Лостмарч",
             "Лотто",
             "Луис Ферауд",
             "Луи Виттон",
             "Лав Паспорт",
             "Лов Кей ту Лайф",
             "Лабин",
             "Лучано Паваротти",
             "Лучиано Сопрани",
             "Люсьен Ферреро Мэтрэ Парфюмер",
             "Лаки",
             "Лю Нише",
             "Луиджи Борелли",
             "Лулу Кастаньет",
             "Лулу Гиннесс",
             "Люксури Концепт",
             "Мак",
             "Мэд эт Лен",
             "Мадлен Вионне",
             "Мэдисон",
             "Мадонна",
             "Магрусс Паола",
             "Мейсон Кривелли",
             "Мейсон Франсис Куркджан",
             "Мэйсон Габриелла Чиффо",
             "Мэйсон Мартин Маржела",
             "Мэйсон Ребатчи",
             "Мезон Таити",
             "Мэтр Парфюмер Эт Гантиер",
             "Мажда Беккали",
             "Маджем",
             "Мэйкин Оф Каннс",
             "Мансера",
             "Мандарина Дак",
             "Маори",
             "Мэп Оф Зэ Харт",
             "Марберт",
             "Марк де ла Моратдиере",
             "Марк Якобс",
             "Марк Джозеф",
             "Марко Поло",
             "Марк Розен",
             "Марк Антуан Барруа",
             "Марселла Воутерс",
             "Мария Кандида",
             "Мария Шарапова",
             "Мэрайя Кэри",
             "МариаЛюкс",
             "Мари Жаннэ",
             "Мариэлла Бурани",
             "Мэрилин Миглин",
             "Мэрлин Монро",
             "Марина Де Бурбон",
             "Марина Мариноф",
             "Марина Пикассо",
             "Марина Спадафора",
             "Марина Яхтинг",
             "Марк Бакстон",
             "Марли",
             "Марни",
             "Маршалл Филд",
             "Мэри-Кейт и Эшли Олсен",
             "Марьядж",
             "Масаки Матсушима",
             "Маскью Милано",
             "Массимо Дьюти",
             "Матье Премье",
             "Мэтью Вильямсон",
             "Маваз Манзор",
             "макс Азриа",
             "Макс Девиль",
             "Макс Мара",
             "Максим Де Пари",
             "Мэй Фэир Ле Кеир",
             "Маззолари",
             "Медикал Бьюти Ресёрч",
             "Мекканиш Роз",
             "Мементо",
             "Мемо",
             "Менард",
             "Мендиттороса",
             "Мео Фушуни",
             "Мерседес Бенз",
             "Мерхис Парфюмс",
             "Мекс",
             "Микеланджело",
             "Микаллеф",
             "Майкл Джексон",
             "Майкл Корс",
             "Мишель Герман",
             "Майкл Кляйн",
             "Мишель Свисс",
             "Микеле Бьянки",
             "Мик Майкл",
             "Мила Шон",
             "Милано Фрагранци",
             "Миллер И Берту",
             "Миллер Харрис",
             "Миммина",
             "Мин Нью-Йорк",
             "Миракулум",
             "Мирко Буффини",
             "Миск",
             "Мисс Королль",
             "Мисс Сиксти",
             "Миссони",
             "Мистраль",
             "Миу Миу",
             "Мизенсир",
             "Моуд Криэшн Мюник",
             "Моджо",
             "Молинард",
             "Молсхейм и Ко",
             "Молтон Браун",
             "Молине",
             "Мона ди Орио",
             "Монарт Парфюмс",
             "Монетс Палетт",
             "Монотема",
             "Монблан",
             "Монталь",
             "Монтана",
             "Монтеграппа",
             "Морабито",
             "Мореск",
             "Морган",
             "Морган Ле Фэй",
             "Моррис",
             "Москино",
             "Муллиум",
             "Музеум Парфюмс",
             "Мьюзик Де Перфюм",
             "Маст-Хэв",
             "Май Перфюмс",
             "Мираргия",
             "Набиль",
             "Наф Наф",
             "Ней-Олеари",
             "Нанетт Лепор",
             "Наоми Кэмпбелл",
             "Наоми Гудсир",
             "Нарцисс Родригес",
             "Насо Ди Раза",
             "Насоматто",
             "Натори",
             "Наутика",
             "Наутилус",
             "Наясья",
             "Назарено Габриэлли",
             "Нила Вермейр Криэшнс",
             "Нежма",
             "НеллиРоди",
             "Неотантрик Фрагрансез",
             "Нэст",
             "Нью Брэнд",
             "Нью-Йорк Янкиз",
             "Нью Йоркер",
             "Нез Ай Нез",
             "Никель",
             "Ники Минай",
             "Николай Парфюмер Криэйтер",
             "Николас Данила",
             "Николь",
             "Николь Фархи",
             "Николь Миллер",
             "Николь Ричи",
             "Ники Де Сен-Фалль",
             "Нико",
             "Нина Ричи",
             "Найн Вест",
             "Нишане",
             "Нобиль 1942",
             "Нобль Рояль",
             "Номенклатур",
             "Норана Парфюмс",
             "Нуво Париж",
             "Нови Плас",
             "Ню Би",
             "Нюаж",
             "Новая Заря",
             "О Пеи Дю Ля Флёр Д' Оранже",
             "Обюссон",
             "Остин Рид",
             "О Д'Итали",
             "Оноре Де Пре",
             "О.Ж Перрин",
             "Обвиус",
             "Океан Пасифик",
             "Одэджо",
             "Один",
             "Одори",
             "Оффичина Дель Эссенце",
             "Оджар",
             "Окки",
             "Оксана Робски",
             "Ольфактив Студио",
             "Ольфаттолоджи",
             "Олибере Парфюмс",
             "Оливер Дурбано",
             "Оливье Стрелли",
             "Омар Шариф",
             "Омния Профюми",
             "Онирико",
             "Оркид Перфюмс",
             "Оренс Парфюмс",
             "Орифлейм",
             "Ориза Л. Легранд",
             "Орлан",
             "Орлов Париж",
             "Ормонд Джейн",
             "Орос",
             "Орто Паризи",
             "Оскар Де Ла Рента",
             "Отто Керн",
             "Принц Жардиньер",
             "Пако Рабан",
             "Пакома",
             "Пакорока",
             "Пальери",
             "Пал Зилери",
             "Палома Пикассо",
             "Памела Андерсон",
             "Панама 1924",
             "Панкалди и Б",
             "Пани Валевска",
             "Паньер",
             "Пануж",
             "Пантеон Рома",
             "Паола Ферри",
             "Паоло Гигли",
             "Паоло Пекора Милано",
             "Пэйпер Пэшн",
             "Парабол",
             "Парах",
             "Парфико",
             "Парфюм Блейз",
             "Парфюм Коллекшн",
             "Парфюм ди Эмпир",
             "Парфюм Дэ Севинь",
             "Парфюм Хэштег",
             "Перфюм Дэ Ваниль",
             "Парфюмери Дженераль",
             "Парфюмери Партикьюлэ",
             "Парфюмс 137",
             "Парфамс БДК",
             "Парфюмс Бомбей 1950",
             "Парфюмс Киро",
             "Парфюмс Дэ Ля Бастид",
             "Парфюмс Дэ Марли",
             "Парфюмс ДэльРээ",
             "Парфюмс Эт Сонтэ Дю Пеи Баск",
             "Парфумс Лайвли",
             "Парфам Софист",
             "Пари Блю Парфам",
             "Пэрис Хилтон",
             "Пэрис Ворлд Лакшери",
             "Парли Мо Дэ Парфам",
             "Пэрур",
             "Паскаль Морабито",
             "Паскаль Шаллер",
             "Патрис Мартин",
             "Патрик Мобуссен",
             "патрициа Пепе",
             "Пол и Джо",
             "Пол Эмилиен",
             "Пол Себастьян",
             "Пол Смит",
             "Паулина Рубио",
             "Пайо",
             "Педро дель Хьеро",
             "Пенхалигон",
             "Пентхаус",
             "Пепе Джинс",
             "Пёфект Сэнс Мэйн",
             "Перфум Джуэлс",
             "Парфюм Най Джиа",
             "Парфюмер'з Воркшоп",
             "Парфюмерия Гал",
             "Перрис",
             "Перри Эллис",
             "ПиЭйч Фрагрансис",
             "Пьер Бальман",
             "Пьер Карден",
             "Пьер Гийом",
             "Пьер Пресьез",
             "Пьер Вульф",
             "Пинайдер",
             "Питбуль",
             "Плейбой",
             "Плюм Импрэшн",
             "Пуаре",
             "Пола",
             "Полис",
             "Помелато",
             "Понти Парфюм",
             "Попи Морени",
             "Порччи",
             "Порш Дизайн",
             "Позитив Парфюм",
             "Пауэлс",
             "Прада",
             "Премьер",
             "Прескрптивс",
             "Прима Материя",
             "Принц",
             "Принц Генри Д Орлеанс",
             "Принц Матчебелли",
             "Присцилла Пресли",
             "Призм Парфюмс",
             "Профуми дэль Фортэ",
             "Профюми Ди Пантеллерия",
             "Профюмо Ди Фиренцэ",
             "Профумум Рома",
             "Пруденс пари",
             "Пуччини",
             "Пума",
             "Пуредистанс",
             "Пипл Оф Зэ Лабиринтс Луктор Эт Эмерго",
             "Парфюмерия XXI Века",
             "Покровка",
             "Реджин",
             "Рала",
             "Раллет",
             "Ральф Лорен",
             "Рамон Бежар",
             "Рамон Молвизар",
             "Рамон Монегал",
             "Рампаж",
             "Рансе",
             "Рания Дж",
             "Расаси",
             "Рэймонд Мэттс",
             "Ре Профумо",
             "Реалм",
             "Рим Акра",
             "Регалиен",
             "Реминисенс",
             "Реми Латур",
             "Реми Маркиз",
             "Рэн",
             "Ренато Балестра",
             "Рене Амбер",
             "Рене Лизар",
             "Рене Соланж",
             "Рени",
             "Ренегейдс",
             "Репетто",
             "Реплэй",
             "Ревелейшн Парфюмс",
             "Ревиллон",
             "Ревлон",
             "Рейни",
             "Ричард Джеймс",
             "Рифат Озбек",
             "Рианна",
             "Ритуалс",
             "Роудс",
             "Роберт Больё",
             "Робер Пиге",
             "Роберто Капуччи",
             "Роберто Кавалли",
             "Роберто Верино",
             "Робски и Собчак",
             "Рокко Барокко",
             "Роша",
             "Родиер",
             "Роже и Галет",
             "Роже Дав",
             "Ромеа Д Амор",
             "Ромео Гигли",
             "Рон Робинсон",
             "Рум 1015",
             "Роос Энд Роос",
             "Роуз и Ко Манчестер",
             "Розендо Матеу Ольфактив Экспрешнс",
             "Руж Банни Руж",
             "Роял Краун",
             "Роял Долтон",
             "Рояль Монсо",
             "РСВ",
             "Рубеус Милано",
             "Рубино Косметикс",
             "СиБи Ай Хэйт Парфюмс",
             "Селин",
             "Селин Дион",
             "Сиэль",
             "Синди Си",
             "Синди Кроуфорд",
             "Сити Парфюм",
             "Смайли",
             "С.Ишира",
             "С.Оливер",
             "Салини",
             "Сент Джеймс",
             "Саледо",
             "Сэлл Прайви",
             "Сальвадор Дали",
             "Сальвадор Ферагамо",
             "Сандалиа",
             "Сандро",
             "Санта Эулалия",
             "Санта Мария Новелла",
             "Санти Бургас",
             "Сара Коннор",
             "Сара Джессика Паркер",
             "Сарантис",
             "Сент бар",
             "Сэнтстори",
             "Скиапарелли",
             "Селена Гомес",
             "Сенсай",
             "Сефора",
             "Серж Дюмонтен",
             "Серж Луи Альварес",
             "Серж Лютанс",
             "Серж Норман",
             "Сержио Неро",
             "Серджио Тачини",
             "Сайбериан Веллнесс",
             "Сигнатюр",
             "Сигнэйче Фрагрансес",
             "Симими",
             "Симонэ Андреоли",
             "Симоне Косак Профюми",
             "Сир Парфюмер",
             "Сислей",
             "Сикс Сентс	",
             "Слава Зайцев",
             "Слезингер",
             "Смайл Париж",
             "Снэп",
             "Снупи Фрагранс",
             "София Вергара",
             "Соланж",
             "Солинотс",
             "Соня Рикель",
             "Соауд",
             "Сорэлле Фонтана",
             "Соспиро Парфюмс",
             "Спада",
             "Спирит Оф Кингс",
             "СпанчБоб Сквээпэнтс",
             "Стейкд Стайл",
             "Старк",
             "Стэйт Оф Майнд",
             "Стефано Кантури",
             "Стефано Риччи",
             "Стэлла Каденте",
             "Стелла Маккартни",
             "Стендаль",
             "Стефан Гумберт Лукас 777",
             "Стефани Де Брюйн",
             "Стерлинг Парфюмс",
             "Саксес де Париж",
             "Суд Пасифик",
             "Сью Вонг",
             "Супердрай",
             "Сьюзан джи Комен Фо Кьюа",
             "Сюзанна Ланг",
             "Сваровски",
             "СвеДофт",
             "Свит Еарз",
             "Свисс Арабиан",
             "Свисс Гард",
             "Сид Джунаид",
             "Сильвен Делакур",
             "Смурфики",
             "Таблю Дэ Парфамс",
             "Талисман Коллеционе Прециоза",
             "Тан Джудичелли",
             "Тан Рока",
             "Тауэр",
             "Тауэрвилль",
             "Таулето",
             "Тайлор Свифт",
             "Театро Фрагранце Унике",
             "Тед Бейкер",
             "Тед Лапидус",
             "Тео Кабанел",
             "Текила",
             "Тереза Хельбиг",
             "Терри де Ганцбург",
             "Темин",
             "Тео Феннел",
             "Тьерри Мюглер",
             "Тёрдмэн",
             "Томас Космала",
             "Тиффани",
             "Тизиана Терензи",
             "Токка",
             "Тодд Олдхэм",
             "Том Дэксон",
             "Том Форд",
             "Том Тэйлор",
             "Томми Суни",
             "Томми Багама",
             "Томми Хилфигер",
             "Тонино Ламборджини",
             "Топ Модель",
             "Торренте",
             "Тори Берч",
             "Тоус",
             "Триш МакЭвой",
             "Тру Брит Лондон",
             "Тру Релиджен",
             "Труссарди",
             "Туига",
             "УЕР МИ",
             "Ульрик Де Вэренс",
             "Ун Нюи Номад",
             "Унис",
             "Уник Парфюм",
             "Унум",
             "Уотерфорд",
             "Ус-Юзак",
             "Фаби",
             "Фэконнэбл",
             "Фэйт Хилл",
             "Фамилиа",
             "Фкук",
             "Фи",
             "Фенди",
             "Феррари",
             "Ферре",
             "Филе Фрагрансэс",
             "Фила",
             "Филиппо Сорчинелли",
             "Фиоруччи",
             "Флирт!",
             "Флораику",
             "Флорена Колниш",
             "Флорис",
             "Флай Фалкон",
             "Фоа",
             "Форэвэ Уд",
             "Фукетс Парфюм",
             "Фрагонар",
             "Фрагранс Ворлд",
             "Франс Папу",
             "Франческо Бианки",
             "Франческа Дель'Оро",
             "Франческо Смалто",
             "Франк Боклет",
             "Франк Мюллер",
             "Франк Оливер",
             "Франсуа Фурнье",
             "Франки Морелло",
             "Фрапин",
             "Фред Хаймен",
             "Фредерик Маль",
             "Фреш",
             "Фрэш Лайн",
             "Фуэгия 1833",
             "Фурла",
             "Фаедон",
             "Фаррелл Уильямс",
             "Филипп Венете",
             "Филли и Филл",
             "Философия",
             "Фуонг Данг",
             "Хлое",
             "Холли Берри",
             "Халстон",
             "Хамиди Уд и Перфюмс",
             "Ханае Мори",
             "Ханора",
             "Хаут Фрагранс Компани",
             "Хаяри",
             "Хинлей",
             "Хелена Рубинштейн",
             "Хельмут Ланг",
             "Хе Вон Иден",
             "Херви Гамбс",
             "Херве Леджер",
             "Хилари Дафф",
             "Хинд",
             "Хироко Кошино",
             "Хистори Де Парфюм",
             "Холлистер",
             "Хорсбол",
             "Хубигант",
             "Хаус оф Силладж",
             "ХСК Париж",
             "Хуберт Маес Криэшнс",
             "Хьюго Босс",
             "Хумиецки и Граф",
             "Хунка",
             "Хлои и Ламар",
             "Хохо",
             "Черутти",
             "Чабауд",
             "Чабравичи",
             "Чарльз Оф Зе Ритц",
             "Чауган",
             "Чкудра",
             "Чино Неро",
             "Чек энд Спик",
             "Шанель",
             "Шанталь Томас",
             "Шантекайл",
             "Шарль Журдан",
             "Шариоль",
             "Шоме",
             "Шопард",
             "Шварцлозе Берлин",
             "Шон Джон",
             "Шейх",
             "Шакира",
             "Шанхай",
             "Шон Мендес",
             "Шей Энд Блю Лондон",
             "Шисейдо",
             "Э Лаб Он Фаэ",
             "Эрин Лаудер",
             "Этэр",
             "Эйр-Вал Интернэшнл",
             "Элисон Олдони",
             "Энди Уорхол",
             "Энгри Бердз",
             "Энимал",
             "Энн Джерард",
             "Энн Мёллер",
             "Эпл Парфам",
             "Эйприл Ароматикс",
             "Эстэ Парфюмс",
             "Эйвери Файн Перфюмери",
             "Эклектик Коллекшн",
             "Эд Харди",
             "Эдди Барклай",
             "Эдвард Бесс",
             "Эгофакто",
             "Эйт энд Боб",
             "Эль Чарро",
             "Электимусс",
             "Эли Сааб",
             "Эли Тахари",
             "Элизир",
             "Элит Модел",
             "Элизабет Энд Джеймс",
             "Элизабет Арден",
             "Элизабет Тейлор",
             "Элла Кей",
             "Элла Микао",
             "Элен Трейси",
             "Элод",
             "Элизе Фешн",
             "Эммануэль Унгаро",
             "Эмешель",
             "Эмилио Пуччи",
             "Эммануэль Левайн",
             "Эмор",
             "Эмпер",
             "Эмпорийом",
             "Энрико Ковери",
             "Энрико Джи",
             "Эрреуно",
             "Эскада",
             "Эксцентрик Молекула",
             "Эсме Рене",
             "Эсприт",
             "Эсприт Дэ Версаль",
             "Эссе Страйкс Зэ Ноутс",
             "Эссэншл Парфюмс",
             "Эстебан",
             "Эсти Лаудер",
             "Эстевиа",
             "Этат Либре Д'оранж",
             "Этро",
             "Этопи",
             "Эвафлор",
             "Эводи Парфюмс",
             "Экс Флорибус Винис",
             "Экс Нихило",
             "Экстэ",
             "Эксума Парфюмс",
             "Эф1 Парфюмс",
             "Эрметика",
             "Эль Артисан",
             "Эм Инт",
             "ЭмДиСиАй Парфюмс",
             "ЭмПиЭф",
             "ЭнВиДо",
             "Эс-Парфюм",
             "ЭсФоПи",
             "ЭсДжи79 ЭсТиЕйджЭлЭм",
             "Ю.с. поло",
             "Ягуар",
             "Ярдли",
             "10 Корсо Комо",
             "1000 Флавэрс",
             "12 Парфюме Франсе",
             "19-69",
             "20-й Век Фокс",
             "24",
             "27 87",
             "4160 Тьюздэйз"]
    bri = []
    c = 0
    brand ="Нет Бренда"

    for br in brands:
        if name.lower().replace(" ", '').find(br.get("name").lower().replace(" ", '')) >= 0:
            brand = br
    if brand =="Нет Бренда":
        for br in BRAND:
            if name.lower().replace(" ", '').find(br.lower().replace(" ", '')) >= 0:
                brand = {"name":br}
    return (name,pol,vid,brand)

def GetCat(cat):
    if cat == "Женская парфюмерия":
      cat = {"categories": [
      {
        "id": 60,
        "name": "Женская парфюмерия",
        "slug": "zhenskaya-parfyumeriya"
      },
    ]}
    elif cat == "Мужская парфюмерия":
        cat = {"categories": [
            {
                "id": 69,
                "name": "Мужская парфюмерия",
                "slug": "muzhskaya-parfyumeriya"
            },
        ]}
    elif cat == "Унисекс":
        cat = {"categories": [
            {
                "id": 155,
                "name": "Унисекс",
                "slug": "uniseks"
            },
        ]}
    else:
        cat = {"categories": [
            {
                "id": 155,
                "name": "Унисекс",
                "slug": "uniseks"
            },
        ]}
    return cat

def GetAtr(atr0,atr1):
    atr = {"attributes": [
        {
            "id": 2,
            "name": "brands",
            "position": 0,

            "options": [
                atr0.get('name')
            ]
        },
        {
            "id": 3,
            "name": "Вид",
            "position": 0,

            "options": [
                atr1
            ]
        }
        ]
    }
    return atr

def AppendMainProd(newProducts,wcapi,brands):

    for data in newProducts:
        print(data.get("name"))
        name,cat,atr1,barand = RenameName(data.get("name"),brands)
        print(name,cat,atr1,barand)
        if name == None or name=='' or barand == 'Нет Бренда':
            continue
        cat = GetCat(cat)
        atr = GetAtr(barand ,atr1)
        dataForMain= {
                "name": name,
                "description": data.get("des"),
                "images": [
                              {

                                "src": data.get("img"),

                              }
                        ],
                "categories": cat.get("categories"),
                "attributes": atr.get("attributes"),
                "grouped_products": [],
                "type": "grouped"


            }
        while True:
            try:
                jsonProd = wcapi.post("products", dataForMain).json()
                break
            except:
                sleep(5)

# def PostDopTov(data,name,priceUSA,wcapi):
#     name = RenameNameProbnik(name,data.get("categories"))
#     if (not CheckTov(name,wcapi)):
#         dataForDop= {
#             "name": name,
#             "description": data.get("description"),
#             "images": data.get("images"),
#             "regular_price": str((int(float(priceUSA.replace(',','.')))*96)*1.1)
#         }
#         jsonProd = wcapi.post("products", dataForDop).json()
#         print(jsonProd)
#         # print(jsonProd.get("id"))
#         grouped_products = []
#         for i in list(data.get("grouped_products")):
#             grouped_products.append(i)
#         grouped_products.append(jsonProd.get("id"))
#         print(grouped_products)
#         dataForMain = {
#             "grouped_products": grouped_products
#             # ....
#
#         }
#     print(wcapi.put("products/"+str(data.get("id")),dataForMain).json())
#

def CheckMainTov(dataproducts,tovar):
    for i in dataproducts:
        if i.get("name").replace(" ","").lower() == tovar.replace(" ","").lower() :
            return True
    return False

#
# def GetCSVProduct(dataproducts,wcapi):
#     with open('lll.csv', 'r', newline='', encoding="utf-8") as csvfile:
#         newtovars = csv.reader(csvfile, delimiter=';', quotechar='|')
#         # for row in spamreader:
#         #     # print(row[1].replace(" ","").lower())
#         #     prod = row[1].split("   ")[0]
#         #     # print(prod)
#         #
#         #     for i in dataproducts:
#         #         if i.get("name").replace(" ","").lower() == prod.replace(" ","").lower() :
#         #             tovar = GetOneTovar(wcapi,i.get("id"))
#         #             # print(i.get("name")+" - "+ row[1])
#         #             # print(RenameNameProbnik(row[1],i.get("categories")))
#         #             #PostDopTov(tovar,row[1],row[2],wcapi)
#     with open('lll.csv', 'r', newline='', encoding="utf-8") as csvfile:
#         duxi = csv.reader(csvfile, delimiter=';', quotechar='|')
#     for i in newtovars:
#         for j in duxi:
#             newtovar = i[1]
#             dux = j[1]
#             # Работаю сострокой
#
#             #
#             if newtovar.find(dux):
#                 if CheckMainTov(dataproducts,newtovar):
#                     #AppendMainTov()
def ReplaceNNP(string):
    string = string.replace(' edp', ' ')
    string = string.replace(' edc', ' ')
    string = string.replace(' edt', ' ')
    string = string.replace(' parfume', ' ')
    string = string.replace('(w)', '')
    string = string.replace('(m)', '')
    string = string.replace('(y)', '')
    return string

def ReplaceD(string):
    string = string.replace('Туалетная вода', '')
    string = string.replace('Парфюмерная вода', '')
    string = string.replace('Туалетная и парфюмерная вода', '')
    string = string.replace('-', '')
    return string.strip()

def GetNewProducts(dataproducts,nameNewProd):
    prod = []
    f = open('test.txt', 'w')
    with open('lll1.csv', 'r', newline='', encoding="utf-8") as csvfile:
        duxi = csv.reader(csvfile, delimiter=';', quotechar='|')
        c=0
        for row in duxi:
            # print(row)
            print(c)
            c+=1
            nameD = row[0]
            nameD = ReplaceD(nameD)
            print(nameD)
            for nnp in nameNewProd:
                nameNNP = ReplaceNNP(nnp)

                if nameD.lower().replace(" ", '') == nameNNP.lower().replace(" ", '') :
                    prod.append({
                        "name": nnp,
                        "mainName":nameNNP,
                        "des": row[1],
                        "img": row[2]
                    })



    print(len(prod))
    input()
    return prod


def GetNames():
    f = open("nameTov.txt")
    ar = f.read().split('\n')
    return ar


def GetOneTovar(wcapi,id):
    return wcapi.get("products/"+str(id)).json()

def GetALLBrand(wcapi):
    page = 1
    brands = []
    while True:
        products = wcapi.get("products/attributes/2/terms", params={'per_page': 100,
                                                 'page': page}).json()
        print(products)
        for i in products:
            brands.append({
                "id": i.get("id"),
                "name": i.get("name"),
            })
        if len(products) == 0:  # no more products
            break
        page = page + 1
    return brands

def main():
    wcapi = GetAPIConnect()
    jsBrands =GetALLBrand(wcapi)
    print(jsBrands)

    dataproducts = GetOLDTovar(wcapi)
    nameNewProd = GetNames()
    newProducts = GetNewProducts(dataproducts,nameNewProd)
    AppendMainProd(newProducts,wcapi,jsBrands)
    # print(newProducts,wcapi)
    #GetCSVProduct(dataproducts,wcapi)


if __name__ == '__main__':
    main()